import { Cairo } from 'next/font/google';
import { routing } from '@/i18n/routing';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { cn } from '@/lib/utils';
import { CalculatorsMobileBar } from '@/components/common/calculators-mobile-bar';
import { Header } from '@/components/common/header';
import { Toaster } from '@/components/ui/sonner';
import '../globals.css';

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

const cairo = Cairo({
  subsets: ['latin', 'arabic'],
  variable: '--font-cairo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const messages = await getMessages();
  const dir = locale === 'ar' ? 'rtl' : 'ltr';
  return (
    <html
      className={cn('h-full', 'antialiased', cairo.variable, 'font-sans')}
      lang={locale}
      dir={dir}
    >
      <body className="flex min-h-full flex-col bg-slate-50">
        <NextIntlClientProvider messages={messages}>
          <Header />
          <CalculatorsMobileBar />
          {children}
          <Toaster position="bottom-center" richColors />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
